import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        surface: '#f7fafc',
        'surface-dim': '#d7dadc',
        'surface-bright': '#f7fafc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f6',
        'surface-container': '#ebeef0',
        'surface-container-high': '#e5e9eb',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#181c1e',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eef1f3',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#455f88',
        primary: '#002045',
        'on-primary': '#ffffff',
        'primary-container': '#1a365d',
        'on-primary-container': '#86a0cd',
        'inverse-primary': '#adc7f7',
        secondary: '#944b00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe9743',
        'on-secondary-container': '#6b3500',
        tertiary: '#4a0008',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#720011',
        'on-tertiary-container': '#ff7170',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        'secondary-fixed': '#ffdcc5',
        'secondary-fixed-dim': '#ffb783',
        'on-secondary-fixed': '#301400',
        'on-secondary-fixed-variant': '#703700',
        'tertiary-fixed': '#ffdad8',
        'tertiary-fixed-dim': '#ffb3b0',
        'on-tertiary-fixed': '#410006',
        'on-tertiary-fixed-variant': '#8c1620',
        background: '#f7fafc',
        'on-background': '#181c1e',
        'surface-variant': '#e0e3e5',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        h1: ['Plus Jakarta Sans', 'sans-serif'],
        h2: ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '20px',
        'container-max': '1200px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
} satisfies Config;

export default config;
